FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY recognizer /recognizer
COPY config.ini /recognizer/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /recognizer
USER appuser

WORKDIR /recognizer
CMD ["python", "recognizer.py", "config.ini"]

