FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY mobile /mobile
COPY config.ini /mobile/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /mobile
USER appuser

WORKDIR /mobile
CMD ["python", "mobile.py", "config.ini"]

EXPOSE 6008