FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY sprayer /sprayer
COPY config.ini /sprayer/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /sprayer
USER appuser

WORKDIR /sprayer
CMD ["python", "sprayer.py", "config.ini"]
