FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY position /position
COPY config.ini /position/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /position
USER appuser

WORKDIR /position
CMD ["python", "position.py", "config.ini"]
