FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY control /control
COPY config.ini /control/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /control
USER appuser

WORKDIR /control
CMD ["python", "control.py", "config.ini"]

EXPOSE 6004