version: '3.4'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  
  broker:
    image: confluentinc/cp-kafka:7.2.0
    container_name: broker
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
      - "9094:9094"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092, OUTSIDE://localhost:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    
  control:
    image: control
    build:
      context: .
      dockerfile: ./Dockerfile.control   
    depends_on:
      - broker 
    ports:
      - "6004:6004"

  monitor:
    image: monitor
    build:
      context: .
      dockerfile: ./Dockerfile.monitor
    depends_on:
      - broker


  dispatcher:
    image: dispatcher
    build:
      context: .
      dockerfile: ./Dockerfile.dispatcher
    depends_on:
      - broker

  position:
    image: position
    build:
      context: .
      dockerfile: ./Dockerfile.position
    depends_on:
      - broker

  mobile:
    image: mobile
    build:
      context: .
      dockerfile: ./Dockerfile.mobile
    depends_on:
      - broker
    ports:
      - "6008:6008"

  connector:
    image: connector
    build:
      context: .
      dockerfile: ./Dockerfile.connector
    depends_on:
      - broker
    ports:
      - "6009:6009"

  recognizer:
    image: recognizer
    build:
      context: .
      dockerfile: ./Dockerfile.recognizer
    depends_on:
      - broker
  
  sprayer:
    image: sprayer
    build:
      context: .
      dockerfile: ./Dockerfile.sprayer
    depends_on:
      - broker

  
