FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY dispatcher /dispatcher
COPY config.ini /dispatcher/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /dispatcher
USER appuser

WORKDIR /dispatcher
CMD ["python", "dispatcher.py", "config.ini"]
