### activate
POST http://0.0.0.0:6009/activate HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    
} 


###
GET http://0.0.0.0:6004/task HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "status": "active"
}


### create new order
POST http://0.0.0.0:6009/new-task HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "x1": 50,
    "y1": 50,
    "z1": 10,
    "expenditure": 10,
    "x2": 55,
    "y2": 55,
    "z2": 10,
    "close_key": 12345
} 
